name: Deploy to VPS

on:
  push:
    branches:
      - deploy  # O cualquier rama que uses

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: |
          docker build \
            --build-arg VITE_STRAPI_URL=${{ secrets.VITE_STRAPI_URL }} \
            --build-arg VITE_STRAPI_GRAPHQL=${{ secrets.VITE_STRAPI_GRAPHQL }} \
            --build-arg VITE_BACKEND_URL=${{ secrets.VITE_BACKEND_URL }} \
            -t xander99/alexanderweb-front:latest .

      - name: Push Docker image to Docker Hub
        run: |
          echo ${{ secrets.DOCKER_HUB_TOKEN }} | docker login -u xander99 --password-stdin
          docker push xander99/alexanderweb-front:latest

      - name: Deploy to VPS via SSH
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.VPS_IP }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.LOCAL_SSH_KEY }}
          script: |
            cd ~/alexanderweb
            docker pull xander99/alexanderweb-front:latest
            docker compose up -d --force-recreate
          # script: |
          #   docker pull xander99/alexanderweb-front:latest
          #   docker stop frontend || true  # Detener el contenedor anterior (si existe)
          #   docker rm frontend || true    # Eliminar el contenedor anterior (si existe)
          #   docker run -d --name frontend -p 3000:80 xander99/alexanderweb-front:latest
